add a basic job summary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -595,12 +595,30 @@ jobs:
         id: combinecoverage
         run: |
           python -m coverage combine
-          python -m coverage report --fail-under=100
+          echo "## Python Coverage" >> $GITHUB_STEP_SUMMARY
+          COV_REPORT=$(python -m coverage report -m --fail-under=100)
+          COV_EXIT_CODE=$?
+          echo $COV_REPORT
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo $COV_REPORT >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          if [ $COV_EXIT_CODE -ne 0 ]; then
+            echo "🚨 Python Coverage failed. Under 100"
+            exit 1
+          fi
       - name: Combine rust coverage and fail if it's <100%.
         id: combinerustcoverage
         run: |
           sudo apt-get install -y lcov
-          lcov $(for f in *.lcov; do echo --add-tracefile "$f"; done) -o combined.lcov | grep lines | grep "100.0%"
+          RUST_COVERAGE_OUTPUT=$(lcov $(for f in *.lcov; do echo --add-tracefile "$f"; done) -o combined.lcov | grep lines)
+          echo "## Rust Coverage" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo $RUST_COVERAGE_OUTPUT >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          if $RUST_COVERAGE_OUTPUT | grep "100.0%"; then
+            echo "🚨 Rust Coverage failed. Under 100"
+            exit 1
+          fi
       - name: Create rust coverage HTML
         run: genhtml combined.lcov -o rust-coverage
         if: ${{ failure() && steps.combinerustcoverage.outcome == 'failure' }}
